services:
    fp_swfupload.session_listener:
        class:                                                     Fp\SwfuploadBundle\EventListener\SessionListener
        arguments:
            -                                                      [] # array of urls.
            -                                                      @router 
        tags:
            -                                                      { name: kernel.event_subscriber }